name: Update Progress

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  update-progress:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Count solved problems
        id: count
        run: |
          SOLVED=$(grep -oi "\- \[[xX]\]" phase-1.5-exploring-patterns/README.md | wc -l)
          echo "solved=$SOLVED" >> $GITHUB_OUTPUT

      - name: Update README
        run: |
          FILE="phase-1.5/README.md"
          TOTAL=20
          SOLVED=${{ steps.count.outputs.solved }}

          PERCENT=$(awk "BEGIN {printf \"%.0f\", ($SOLVED/$TOTAL)*100}")
          BLOCKS=$(awk "BEGIN {print int($PERCENT/5)}")

          BAR=""
          for ((i=0;i<20;i++)); do
            if [ $i -lt $BLOCKS ]; then
              BAR="${BAR}█"
            else
              BAR="${BAR}░"
            fi
          done

          sed -i "s/<!-- SOLVED_COUNT -->.*<!-- \/SOLVED_COUNT -->/<!-- SOLVED_COUNT -->$SOLVED<!-- \/SOLVED_COUNT -->/" $FILE
          sed -i "s/<!-- PROGRESS_PERCENT -->.*<!-- \/PROGRESS_PERCENT -->/<!-- PROGRESS_PERCENT -->$PERCENT<!-- \/PROGRESS_PERCENT -->/" $FILE
          sed -i "/<!-- PROGRESS_BAR -->/,/<!-- \/PROGRESS_BAR -->/c\\<!-- PROGRESS_BAR -->\n[$BAR] $PERCENT%\n<!-- /PROGRESS_BAR -->" $FILE

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add phase-1.5/README.md
          git diff --cached --quiet || git commit -m "Auto update progress"
          git push
